### PR TITLE
Pass environment to WHERE and RETURNING subexpressions of the DELETE FROM statement

### PR DESCRIPTION
**Pull request by villesokk**
This is pretty minimal. Just enough to get DELETE FROM statements with WHERE or RETURNING to typecheck.

### CODE REVIEW

**Comment by JakeWheat** [comment]
Hi, thanks for the request. Can you add some simple type check tests for these changes? One or two tests for where and for returning would be good.

**Comment by villesokk** [comment]
I added some tests but I only test things that are actually checked by the typechecker. For example, there is still no check that the where condition is a boolean.

**Comment by JakeWheat** [comment]
Sorry for the incredibly long delay, thanks for the tests as well.

**Comment by villesokk** [comment]
Thank you. I never expected this to get merged : P

**Pull request merged**
